### ISSUE TITLE
[22.09.16] Debuging JS & React

### ISSUE THREAD

**Issue by vicnbt** [wiley-ui-public/korolev-microconf#1]
presentation : https://docs.google.com/presentation/d/16tLWnFB_riaraeHPy51n93G5s3ztTGehw6XXV8LiQ5Q/edit#slide=id.p

**Comment by vicnbt** [comment]
Async satck trace with promise.all

var p1 = new Promise(promise1 = function(resolve, reject){  setTimeout(resolve, 103, "foo");}); 
var p2 = new Promise(promise2 = function(resolve, reject){  setTimeout(resolve, 101, "bar");}); 
var p3 = new Promise(promise3 = function(resolve, reject){  setTimeout(resolve, 100, "baz");}); 
f = function(){  console.log("what in the async stack?"); }
Promise.all([p1, p2, p3]).then(values => {  f(); });
debug(f);

![image](https://cloud.githubusercontent.com/assets/2864268/18782845/1a8c935c-8191-11e6-83f4-2812b10a744c.png)

**Comment by vicnbt** [comment]
Нашел дополнительную возможность отладки в IE
иногда после остановки на точке останова и продолжения выполнения IE зависает
и отлаживать можно только с помощью console.log

а если менять исходники нет возможности, например нужно отладить уже задеплоенную версию 
на помощь приходит Insert Tracepoint

![image](https://cloud.githubusercontent.com/assets/2864268/18831455/589c6852-83ee-11e6-87c3-f4a1a271f6fe.png)

**Comment by vicnbt** [comment]
Добавлю ещё сюда комментарий Александра:

Aleksandr Yavorskiy:
Вчера после митинга посмотрел, оказалось в ES7 есть Object.observe, Array.observe (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/observe)
Еще наткнулся на статью по отладке с async:
https://habrahabr.ru/post/218397/

**Comment by yavalvas** [comment]
Константин уточнил, что Object.observe - depricated, хотя могло бы выручить в некоторых ситуациях, если бы потребовалось выявить, где и как изменялся объект.

**Comment by vicnbt** [comment]
хочу ещё отметить, что использование горячих клавиш, значительно ускоряет отладку

**Comment by vicnbt** [comment]
небольшой трюк, позволяющий сохранить содержимое выведенной с помощью console.log переменной в буфер:

![author services - google chrome](https://cloud.githubusercontent.com/assets/2864268/19142358/8a2e81de-8ba5-11e6-8076-143573d67504.jpg)

**Comment by vicnbt** [comment]
test

**Comment by vicnbt** [comment]
debugger я использую в коде как 

debugger;//fixme (vnabatov)

(//fixme (vnabatov) добавляется через алиас !td<TAB>)

а также необходимо добавить в eslint правило
"no-debugger": 0,//fixme (vnabatov)

контроль против коммита - добавил правило запрета коммита с //fixme (vnabatov) в IDEA.

**Comment by vicnbt** [comment]
![image](https://cloud.githubusercontent.com/assets/2864268/19394612/9975c0c8-9242-11e6-98fe-5bc161b1d8a8.png)

**Comment by vicnbt** [comment]
для отлова изменений DOM

**Comment by vicnbt** [comment]
Денис подсказал как отлаживать удаленный сайт с локальными скриптами

1. скачиваем https://www.telerik.com/download/fiddler
2. открываем вкладку AutoResponder
3. включаем Enable Rules и Unmatched requests passthrough
4-5. Добавляем REGEX:.+/spa/.+/(.*\.js) и http://localhost:8084/spa/2.0.0-iteration.10-285-g249cadb/$1

возможно нужно будет дополнительно включить поддержку HTTPS
