### ISSUE TITLE
[19.01.2017] tech lead - every day work, Q&A Sessions

### ISSUE THREAD

**Issue by chaos-adept** [wiley-ui-public/korolev-microconf#26]

**Comment by chaos-adept** [comment]
> так же я был бы рад послушать про техлидовский опыт Дениса. С какими подводными камнями столкнулся, как принимаются решения и как вообще проходит процесс управления командой

**Comment by vicnbt** [comment]
Дополнительные вопросы, на которые можно ответить в рамках конференции
Некоторые общие, некоторые больше относятся к нашей текущей работе

1. Описание решения какой-то сложной проблемы (не технической)
2. Как много времени отнимают отчеты и как из отчетов понять реальный прогресс, какие инструменты помимо JIRA используются 
3. Что дополнительно пришлось изучить для обеспечения успешной работы 
4. Как планируется распределить ресурсы на будущие проекты
5. Насколько лояльны к увеличению сроков и как решаются подобные вопросы
6. Как мы можем увеличить эффективность работы команды (можно даже послушать предложения от команды и сразу получить ответы)
7. Можем ли мы брать какие-то "медленные" проекты для дополнительной разработки или на это сейчас нет ресурсов
8. Озвучить какое планируется расширение команды и на что будут тратится новые ресурсы
9. Как удается быстро переключать контекст между задачами и вникать в проблему
10. Что самое приятное/неприятное в работе (если есть) и как можно это исправить

я виду цель конференции в следующем: узнать про опыт Дениса и поговорить об улучшении качества работы команды

**Comment by archangel-irk** [comment]
Будет ли какая-то практика посвящать ~20% времени сторонним проектам, не связанным с основной деятельностью? Может быть можно получить такое после одобрения менеджера для каждого такого случая. Может быть такие проекты будут как-то контролироваться?

**Comment by archangel-irk** [comment]
Рассказать про свой обычный день, какие задачи обычно решаешь?

**Comment by archangel-irk** [comment]
Сколько времени уходит на разговоры с разработчиками/менеджерами/кодингом?

**Comment by PublicFess** [comment]
Меня очень волнует вопрос метрик и определения сроков. Денис, если есть возможность расскажи, пожалуйста, о:

1. Какие метрики используются для команды и для каждого отдельно
2. Как эти метрики позволяют определить эффективность работы команды в целом
3. Как определяются сроки на задачи, скоп на итерацию. Как попадать в эти сроки?

**Comment by chaos-adept** [comment]
-----

> Описание решения какой-то сложной проблемы (не технической)
- проблема , иногда приходят люди которые хотят поиграть в технолгии после пиара какой то (либы, тулы, фреймворка, подхода)
- решение , изучение тула, дейтсвительно ли он несет профит для проекта, иногда он отклоняется(чаще всего) , иногда он действительно нужен и полезен, как webpack
> Как много времени отнимают отчеты и как из отчетов понять реальный прогресс, какие инструменты помимо JIRA используются
- по требованию, чаще всего начинаю разбираться со всеми возможными метриками для анализа проблем/проблемы
> Что дополнительно пришлось изучить для обеспечения успешной работы
- как только первый раз пришлось лидить программистов, читал книгу - "Как пасти котов", книга интерсная, но практически мало применима, в основном спортивный, педагогический опыт работы инструктором рукопашного и ножевого боя

> Как планируется распределить ресурсы на будущие проекты
- вопрос про WPP? ресурсы будут распределяться по техлилдам, по требованию предоставляться, в другие проекты

> Насколько лояльны к увеличению сроков и как решаются подобные вопросы
- мы сообщество у нас одна цель, если увелечение сроков укладывается в цель это ок, но чаще всего перерасход ресурсов, воспринимается не с радостью

> Как мы можем увеличить эффективность работы команды (можно даже послушать предложения от команды и сразу получить ответы)
- линия доклада, улучшать эффектность нодов кластера ставить больше железа, оптимизировать алгоритмы работы синхронизации

> Можем ли мы брать какие-то "медленные" проекты для дополнительной разработки или на это сейчас нет ресурсов
- что есть медленные проекты? фоновые проекты? вопрос к Артему

----

> Озвучить какое планируется расширение команды и на что будут тратится новые ресурсы
- еще 5ть человек, тратиться на SPR им декомпозицию AS

> Как удается быстро переключать контекст между задачами и вникать в проблему
- не уверен, что это про меня, =) но как и в программировании находится баланс в уровне абстракции

> Что самое приятное/неприятное в работе (если есть) и как можно это исправить
- приятное наличие инструментов влиять на ситуацию, неприятное, что много политики, исправить, удалить всем фантазию и стать тираном =) (шутка)

> Рассказать про свой обычный день, какие задачи обычно решаешь?
- обыночно работа над высокоуровневыми, задачами - по типу ускорить мануальное прокликивание релиза на N часов, это целый комплекс работы, письма менторства, обычно много разговоров

> Сколько времени уходит на разговоры с разработчиками/менеджерами/кодингом?
- большую часть времени идут разговоры, с разработчиками внутри команды, после с другими лидами, дальше в порядке убывания с менеджерами, и по остаточному принципу кодинг (фактически его нет)


> Какие метрики используются для команды и для каждого отдельно
- мера всем вещам, - цель сообщества, все что способствует цели имеет знак +, что противоречит знак -

> Как эти метрики позволяют определить эффективность работы команды в целом
- соотвествие целям cross команд, компании

> Как определяются сроки на задачи, скоп на итерацию. Как попадать в эти сроки?
- по разному иногда сверху, иногда с низу, как попасть, оценка, план, трекинг на ранних и поздних стадиях, как попасть в срок означает не уходить как в плюс так и вминус, для этого существуют оригинальные естимейты и анализ (ответ капитана очевидность, но вопрос поставлен как общий)

**Comment by chaos-adept** [comment]
тема будет закрыта после линковки артефактов и видео

**Comment by archangel-irk** [comment]
Видео доклада
https://www.youtube.com/watch?v=-DMNGq8YUy4

**Comment by chaos-adept** [comment]
Слайды доклада - https://drive.google.com/file/d/0B4qpelV5K0Ghb0VJNUtzNUJwc0U/view?usp=sharing
