### ISSUE TITLE
[19.01.2017] Vote

### ISSUE THREAD

**Issue by PublicFess** [wiley-ui-public/korolev-microconf#27]

**Comment by PublicFess** [comment]
[tech lead - every day work, Q&A Sessions] - Denis Rykovanov

**Comment by PublicFess** [comment]
[Memory and perfomance leaks] - Victor Nabatov

**Comment by vicnbt** [comment]
[Server side rendering] - Victor Nabatov
если у кого-то есть опыт, уступлю тему, сам планирую разобраться и рассказать вступление с несколькими примерами
