### ISSUE TITLE
[6.10.2016] Asynchronous Javascript

### ISSUE THREAD

**Issue by yavalvas** [wiley-ui-public/korolev-microconf#3]
1. Asynchronous, blocking/non-blocking, single-threaded/concurrent Javascript.
2. Javascript functions for simulation of asynchronous execution.
3. Approaches to handle asynchronous execution: 
- Callback functions,
- Promises, Deferreds
- Generators
- Coroutines
- Async/Await.
4. How it currently works under the hood in WPP project (transpilers, presets, babel, bluebird, syntax-async-function).
5. Tasks and Queues.
6. Multithreaded execution of Javascript (Webworkers).
Something of this list of topics can be changed or removed to another day.

**Comment by vicnbt** [comment]
Пример deferred


```
// нужно дождаться конца всей анимации
var a1 = $.Deferred(),
      a2 = $.Deferred();

$('#d1').slideUp(2000, a1.resolve);
$('#d2').fadeOut(4000, a2.resolve);

a1.done(function() { console.log('a1'); });
a2.done(function() { console.log('a2'); });
$.when(a1, a2).done(function() { console.log('both'); });

```

**Comment by yavalvas** [comment]
Here is a link to presentation: [asynchronous-javascript](https://slides.com/yavalvas/asynchronous-javascript)
Article about terms "task", "microtask": [Tasks, microtasks in JS](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/)
Translation of this article: [Tasks, microtasks in JS, Rus](https://habrahabr.ru/post/264993/)
Event loop and workers: [Event loop](https://developer.mozilla.org/ru/docs/Web/JavaScript/EventLoop)
Specification Promises/A+: [Promises/A+](https://github.com/promises-aplus/promises-spec)
Async/await specification: [ecmascript-asyncawait](https://github.com/tc39/ecmascript-asyncawait)
External script loading: [external-script](https://learn.javascript.ru/external-script)
Asynchronous module definition: [AMD](http://requirejs.org/docs/whyamd.html)
W3C web-workers: [Workers](https://www.w3.org/TR/workers/)

**Comment by vicnbt** [comment]
this day was a palindrom day! (6 1 0 2 0 1 6)
6 10 2016 | 6102 01 6

**Comment by vicnbt** [comment]
по воркерам можно отдельную встречу провести,
