### ISSUE TITLE
[27.01.2017] Vote

### ISSUE THREAD

**Issue by chaos-adept** [wiley-ui-public/korolev-microconf#32]

**Comment by chaos-adept** [comment]
[Wiley Org-structure]
https://github.com/wiley-ui-public/korolev-microconf/issues/31
speaker - @abereznyat

**Comment by chaos-adept** [comment]
[Wiley Org-structure]
https://github.com/wiley-ui-public/korolev-microconf/issues/31
speaker - @abereznyat

**Comment by chaos-adept** [comment]
Менеджер: Мифы и Реальность
https://github.com/wiley-ui-public/korolev-microconf/issues/33

спикер @abereznyat

**Comment by abereznyat** [comment]
Wiley projects - WPP
[#34](https://github.com/wiley-ui-public/korolev-microconf/issues/34)

спикеры @gkhristich + @aleskovets

**Comment by vicnbt** [comment]
JS Memory leaks
#11

**Comment by Nachasic** [comment]
Web Components & Custom Elements
#37 

спикер @Nachasic

**Comment by sorcal** [comment]
CI/CD for WEL Mobile Project
[#36](https://github.com/wiley-ui-public/korolev-microconf/issues/36)

@Nachasic
