### ISSUE TITLE
Менеджер: Мифы и Реальность

### ISSUE THREAD

**Issue by chaos-adept** [wiley-ui-public/korolev-microconf#33]
возможные тезисы
* введение понятий менеджера
* как эти понятия представляются на практике
* это правда, что менеджеры пьют кровь новорожденных программистов на своей шикарной Яхте в средиземном море?

спикер @abereznyat

**Comment by abereznyat** [comment]
Если у кого-то есть конкретные вопросы на которые он хотел бы получить развёрнутый ответ, либо хотел бы чтобы какая-то конкретная тема была затронута, пожалуйста набрасывайте ваши мысли здесь.

**Comment by PublicFess** [comment]
Эстимейты. Эсмейты фичи. Эстимейты итерации. Эстимейты проекта.

Мне было бы очень интересно послушать про все что касается определения сроков на административном уровне.

**Comment by archangel-irk** [comment]
1. Что есть менеджер в понимании wiley korolev (менеджеры везде разные)? Какие менеджеры есть у нас в компании?
2. Какие рабочие моменты наиболее сложные для менеджера и почему? Может есть примеры (где все персонажы вымышленные, разумеется).
3. Что делать если подчинённые/руководство дарят личный подарок?

**Comment by Alexxx666** [comment]
1) Может ли IT-проект быть успешным, если во главе стоит человек, знания которого в этой сфере слабы или вообще отсутствуют? Перефразируя - может ли непрограммист успешно управлять программистами?
2) По каким признакам можно понять, что у человека есть потенциал стать хорошим менеджером?

**Comment by chaos-adept** [comment]
ссылка на слайды https://drive.google.com/file/d/0B4qpelV5K0GhbXVpSVJ3dC1TUlU/view?usp=sharing

**Comment by chaos-adept** [comment]
видео - https://www.youtube.com/watch?v=AQTk8jJXURA

**Comment by chaos-adept** [comment]
видео с конф комнаты - https://www.youtube.com/watch?v=6CJ1pcz4AK4&index=7&t=3941s&list=PL4e-U8lyez1jsM4wXXMDAMUDJy2wvuOsj
