### ISSUE TITLE
CI/CD for WEL Mobile Project

### ISSUE THREAD

**Issue by schekhlov** [wiley-ui-public/korolev-microconf#36]
- My Objectives
   - CI/CD for WEL Mobile Project
 - WEL Mobile Project Overview
   - Web App
   - iOS App
   - Android App
 - Technology Stack
   - Javascript
   - React Native
 - Workflow
   - Git-Flow
   - Pre-commit hook
   - Code Review
 - Continuous Integration
   - TeamCity
   - Unit tests
   - SonarQube
   - Code coverage
 - Continuous Delivery
   - FTP
 - Roadmap
   - Improve Continuous Delivery (upload to AppStore)
   - Documentation Generator
   - Increase Code coverage
   - JIRA Integration

**Comment by vicnbt** [comment]
\\emc\Exchange\microconf\2017.03.02 - CI_CD for WEL Mobile Project
