### ISSUE TITLE
[09.02.2017] — Web Components & Custom Elements

### ISSUE THREAD

**Issue by Nachasic** [wiley-ui-public/korolev-microconf#37]
W3C specs condition and adoption rate. Vanilla JS custom elements, Polymer elements, Polymer 2.0 and native component-based UI architecture. Polymer workflow and testing.

**Comment by chaos-adept** [comment]
please assign correct type of this meeting is it overview?

**Comment by chaos-adept** [comment]
slides - https://docs.google.com/presentation/d/1fgU0trJKTsF77Y2W-tD12kM3sBdIsPNXGfbMXqhDMHI/pub?slide=id.p

video - https://www.youtube.com/watch?v=6EiJhtEMe2Q
