### ISSUE TITLE
Rollout overview: CI/CD pipeline and automation of everything

### ISSUE THREAD

**Issue by chaos-adept** [wiley-ui-public/korolev-microconf#46]
Rollout overview: CI/CD pipeline and automation of everything
1. What is DevOps?
2. What is CI/CD pipeline?
3. Functional and Structural testing and Test Cases
4. Automation testing - evolution of view

speaker: Terlov Fedor - Hoboken fterlov@wiley.com

**Comment by archangel-irk** [comment]
Video: https://youtu.be/WBxzCyM2ey4
