### ISSUE TITLE
[20.02.2017] - Unit Tests vs Integration Tests vs Automation Tests: Why? Where? When?

### ISSUE THREAD

**Issue by chaos-adept** [wiley-ui-public/korolev-microconf#48]
Note: it is not a lection, it is conference/holywar. please take with you fire in the heart or at least your fire in the hands.

**Comment by vicnbt** [comment]
https://www.youtube.com/watch?v=piB3CaRXkQY

https://github.com/polarnik/TypesOfTesting - типы тестирования
http://www.protesting.ru/

http://www.duncannisbet.co.uk/test-automation-basics-levels-pyramids-quadrants
http://jamescrisp.org/2011/05/30/automated-testing-and-the-test-pyramid/
http://blog.goneopen.com/2010/08/test-automation-pyramid-review/
https://www.agileconnection.com/article/continuous-testing-building-quality-your-projects?page=0%2C0
http://lisacrispin.com/2011/11/08/using-the-agile-testing-quadrants/
