### ISSUE TITLE
[13.10.2016] JS Generators

### ISSUE THREAD

**Issue by AGanyushkin** [wiley-ui-public/korolev-microconf#6]
generators
generators or/and async
generators, for what?

**Comment by yavalvas** [comment]
It'll be also possible to write generator expressions in the future:
[http://wiki.ecmascript.org/doku.php?id=harmony:generator_expressions](Generator expressions)
Array comprehensions won't be in standart [https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Array_comprehensions](Array comprehensions).
There is a way of writing iterators by "magic" methods by this way (~ES7):
```
function xrange(low, high) {  
    return {
        __iterator__: function() {
            return {  
                next: function() {
                    if (low > high)
                        throw StopIteration;  
                    return low++;
                }
            }
        }
    }
}
```
It can be used in "for i in ..." construction.
Symbol.iterator can be also used to add behaviour of iterator:
```
function xange(start, end) {
    var ret = {};
    ret[Symbol.iterator] = function *() {
        while (start < end) 
            yield start++;
    }
    return ret;
}
for (var x of xange(1, 10))
```

**Comment by AGanyushkin** [comment]
> It can be used in "for i in ..." construction.
for i **of**
